### ISSUE TITLE
feature request: package manager configuration

### ISSUE THREAD

**Issue by dargonforce** [joshiemoore/squidpm#12]
configuration should probably be handled from a shell file that sets variables, and is directly sourced by squidpm.sh

configuration options include things like PREFIX=, CC=, etc

**Comment by joshiemoore** [comment]
Added basic external config in 6ac8aa8a34bbab7793aca1441b04f41ed1b4848f
Will continue to expand as I think of things that need to be configged externally

**Comment by dargonforce** [comment]
Awesome :)
